### PR TITLE
Memory Management: Block readahead, locking

### PR DESCRIPTION
**Pull request by hstern**

### CODE REVIEW

**Comment by vixie** [comment]
stylistically speaking...

+#if defined(HAVE_MLOCK)
+		if (!mlock(r->data+r->t.index_block_offset, mtbl_fixed_decode32(r->data + r->t.index_block_offset) + 2 * sizeof(uint32_t))) {
+			return mtbl_res_success;
+		} else {
+			return mtbl_res_failure;
+		}
+#else
+		return mtbl_res_failure;
+#endif

should put ()'s around the return expressions, and should not use
{braces} around single-statement if/else arms.

**Comment by hstern** [comment]
I bracketed the returns and pushed a replacement commit.  I'm going to keep the braces around the single-statement if/else arms to avoid issues like gotofail.

**Comment by vixie** [comment]
> Henry Stern <mailto:notifications@github.com>
> Monday, January 19, 2015 9:40 AM
>
> I bracketed the returns and pushed a replacement commit. I'm going to
> keep the braces around the single-statement if/else arms to avoid
> issues like gotofail.
>
i suggest that coding style changes are not a good single-actor
case-by-case topic, and that existing style as seen elsewhere in that
source file be your guide until/unless we reach consensus on a
"gotofail" change.

-- 
Paul Vixie

**Comment by hstern** [comment]
This isn't necessary now as we are doing some other madvise tricks.

**Pull request closed without merging**
